-- Zamanla bagli funksiyalar


PRINT GETDATE()
PRINT SYSDATETIME()
PRINT SYSDATETIMEOFFSET()



SELECT DATEADD(DAY, 10, GETDATE())
SELECT DATEADD(MONTH, 10, GETDATE())
SELECT DATEADD(YEAR, 10, GETDATE())



PRINT DAY(GETDATE())
PRINT MONTH(GETDATE())
PRINT YEAR(GETDATE())




PRINT DATEDIFF(DAY, '1992-12-08', SYSDATETIME())
PRINT DATEDIFF(MONTH, '1992-12-08', SYSDATETIME())
PRINT DATEDIFF(YEAR, '1992-12-08', SYSDATETIME())



PRINT DATEPART(DW, '1992-12-08') -- +1
PRINT DATEPART(MONTH, '1992-12-08')
PRINT DATEPART(YEAR, '1992-12-08')







-- Reqemlerle bagli funksiyalar


PRINT PI()
PRINT SIN(92.7)
PRINT POWER(2, 3)
PRINT RAND()
PRINT ABS(-5)
PRINT FLOOR(5.9)
PRINT CEILING(5.1)





-- Metinle bagli funksiyalar

SELECT LEFT(Code, 2) FROM Books
SELECT RIGHT(Code, 2) FROM Books
SELECT UPPER(Publisher) FROM Books
SELECT LOWER(Publisher) FROM Books
SELECT SUBSTRING(Publisher, 2, 5) FROM Books
SELECT LTRIM('   HAKUNA    ')
SELECT LEN(RTRIM('   HAKUNA    '))
SELECT TRIM('   HAKUNA    ')


SELECT REVERSE(Publisher) FROM Books
SELECT REPLACE(Publisher, 'BHV', 'STEP') FROM Books